name: Build and Release

on: [push]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore .NET Tools
      run: dotnet tool restore
      working-directory: ./tests/UnitTests

    - name: Dotnet Build (Release)
      run: dotnet build -c Release
      
    - name: Save SDK Packages
      uses: actions/upload-artifact@v3
      with:
        name: sdk-packages
        path: |
          src/bin/Release/*.nupkg
          src/bin/Release/*.snupkg
          
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ${{ github.workspace }}/coverage/lcov.info


  publish-sdk:
    name: Publish SDK Binaries
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'ooples/OoplesFinance.YahooFinanceAPI' && startsWith(github.ref, 'refs/tags/sdk')

    steps:
    - name: Load SDK Packages
      uses: actions/download-artifact@v3
      with:
        name: sdk-packages

    - name: Create NuGet Version
      run: dotnet nuget push **.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: SDK ${{ github.ref }}
        draft: true
